version: '3.9'
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: ['bin/rails', 'server', '-b', '0.0.0.0']
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
    ports:
      - '3000:3000'
    volumes:
      - bundle:/app/vendor/bundle
      - ./backend:/app
    depends_on:
      - db
  web:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    command: ['pnpm', 'dev']
    environment:
      HOST: '0.0.0.0'
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    ports:
      - '3001:3001'
volumes:
  db-data:
    driver: local
  bundle:
  node_modules:
