inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "config/**/*"
    - "config.ru"
    - "db/migrate/*"
    - "db/schema.rb"
    - "log/**/*"
    - "lib/**/*"
    - "public/**/*"
    - "test/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".irbrc"
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false
